// Unity C# loader stub template. `render()` fills in the placeholders with values compiled from
// the WorldDocument; the generated script is a genuine, compilable starting point (reads
// manifest.json from StreamingAssets, walks the entity list, logs what it would instantiate) —
// NOT a "real" glTF-at-runtime loader (that needs a GLTFast/UnityGLTF package dependency this
// worker can't assume the target Unity project has installed), which is why every instantiation
// point is a clearly marked TODO rather than a silent no-op pretending to load geometry.
export const UNITY_LOADER_TEMPLATE = `// AUTO-GENERATED by @sonic-gameworld/worker-builds — do not hand-edit.
// World: {{WORLD_NAME}} ({{WORLD_ID}})
// Generated: {{GENERATED_AT}}
// Entities: {{ENTITY_COUNT}}
using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace GameWorld
{
    /// <summary>
    /// Loads the GameWorld manifest for "{{WORLD_NAME}}" and instantiates its entities.
    /// Expects manifest.json alongside this script's StreamingAssets deployment
    /// (Assets/StreamingAssets/GameWorld/{{WORLD_ID}}/manifest.json).
    /// </summary>
    public class GameWorldLoader : MonoBehaviour
    {
        [SerializeField] private string manifestRelativePath = "GameWorld/{{WORLD_ID}}/manifest.json";

        private void Start()
        {
            string path = Path.Combine(Application.streamingAssetsPath, manifestRelativePath);
            if (!File.Exists(path))
            {
                Debug.LogError($"[GameWorldLoader] manifest not found at {path}");
                return;
            }

            string json = File.ReadAllText(path);
            GameWorldManifest manifest = JsonUtility.FromJson<GameWorldManifest>(json);
            Debug.Log($"[GameWorldLoader] Loaded manifest for world '{manifest.world.name}' with {manifest.entities.Length} entities");

            foreach (var entity in manifest.entities)
            {
                SpawnEntity(entity);
            }
        }

        private void SpawnEntity(GameWorldEntity entity)
        {
            var go = new GameObject(entity.name);
            go.transform.position = new Vector3(entity.transform.position.x, entity.transform.position.y, -entity.transform.position.z); // glTF (right-handed, Z-forward) -> Unity (left-handed, Z-forward): negate Z
            go.transform.rotation = new Quaternion(entity.transform.rotation.x, entity.transform.rotation.y, -entity.transform.rotation.z, -entity.transform.rotation.w);
            go.transform.localScale = new Vector3(entity.transform.scale.x, entity.transform.scale.y, entity.transform.scale.z);

            if (entity.assetUrl != null && !string.IsNullOrEmpty(entity.assetUrl.assetId))
            {
                // TODO: resolve entity.assetUrl.assetId/variant to a downloaded .glb (or a
                // pre-imported Unity prefab, once the marketplace CDN <-> Unity asset pipeline is
                // wired up) and instantiate it under 'go', instead of a bare empty GameObject.
                Debug.Log($"[GameWorldLoader] TODO: load asset {entity.assetUrl.assetId} (variant {entity.assetUrl.variant}) onto '{entity.name}'");
            }
        }
    }

    [Serializable] public class GameWorldManifest { public WorldInfo world; public GameWorldEntity[] entities; }
    [Serializable] public class WorldInfo { public string id; public string name; }
    [Serializable] public class GameWorldEntity { public string id; public string kind; public string name; public TransformDto transform; public AssetUrlDto assetUrl; }
    [Serializable] public class TransformDto { public Vec3Dto position; public QuatDto rotation; public Vec3Dto scale; }
    [Serializable] public class Vec3Dto { public float x; public float y; public float z; }
    [Serializable] public class QuatDto { public float x; public float y; public float z; public float w; }
    [Serializable] public class AssetUrlDto { public string assetId; public string versionId; public string variant; }
}
`;

export function renderUnityLoader(vars: { worldId: string; worldName: string; generatedAt: string; entityCount: number }): string {
  return UNITY_LOADER_TEMPLATE.replace(/\{\{WORLD_ID\}\}/g, vars.worldId)
    .replace(/\{\{WORLD_NAME\}\}/g, vars.worldName)
    .replace(/\{\{GENERATED_AT\}\}/g, vars.generatedAt)
    .replace(/\{\{ENTITY_COUNT\}\}/g, String(vars.entityCount));
}
