// Unreal C++ loader stub templates (header + source). Same honesty rule as the Unity template:
// this parses the manifest and logs what it would spawn, with a clearly marked TODO where a real
// project would plug in its glTF import pipeline (e.g. glTFRuntime) — it does not pretend to
// spawn real geometry it has no way to load in a headless code-generation context.
export const UNREAL_HEADER_TEMPLATE = `// AUTO-GENERATED by @sonic-gameworld/worker-builds — do not hand-edit.
// World: {{WORLD_NAME}} ({{WORLD_ID}})
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "GameWorldLoader.generated.h"

UCLASS()
class AGameWorldLoader : public AActor
{
    GENERATED_BODY()

public:
    AGameWorldLoader();

    UPROPERTY(EditAnywhere, Category = "GameWorld")
    FString ManifestRelativePath = TEXT("GameWorld/{{WORLD_ID}}/manifest.json");

protected:
    virtual void BeginPlay() override;

private:
    void LoadManifest();
    void SpawnEntity(const TSharedPtr<class FJsonObject>& EntityJson);
};
`;

export const UNREAL_SOURCE_TEMPLATE = `// AUTO-GENERATED by @sonic-gameworld/worker-builds — do not hand-edit.
// World: {{WORLD_NAME}} ({{WORLD_ID}})
// Generated: {{GENERATED_AT}}
// Entities: {{ENTITY_COUNT}}
#include "GameWorldLoader.h"
#include "Dom/JsonObject.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"

AGameWorldLoader::AGameWorldLoader()
{
    PrimaryActorTick.bCanEverTick = false;
}

void AGameWorldLoader::BeginPlay()
{
    Super::BeginPlay();
    LoadManifest();
}

void AGameWorldLoader::LoadManifest()
{
    const FString FullPath = FPaths::Combine(FPaths::ProjectContentDir(), TEXT("GameWorld"), ManifestRelativePath);
    FString JsonString;
    if (!FFileHelper::LoadFileToString(JsonString, *FullPath))
    {
        UE_LOG(LogTemp, Error, TEXT("[GameWorldLoader] manifest not found at %s"), *FullPath);
        return;
    }

    TSharedPtr<FJsonObject> Root;
    TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(JsonString);
    if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid())
    {
        UE_LOG(LogTemp, Error, TEXT("[GameWorldLoader] failed to parse manifest JSON"));
        return;
    }

    const TArray<TSharedPtr<FJsonValue>>* Entities;
    if (Root->TryGetArrayField(TEXT("entities"), Entities))
    {
        UE_LOG(LogTemp, Log, TEXT("[GameWorldLoader] Loaded manifest for world '{{WORLD_NAME}}' with %d entities"), Entities->Num());
        for (const TSharedPtr<FJsonValue>& EntityValue : *Entities)
        {
            SpawnEntity(EntityValue->AsObject());
        }
    }
}

void AGameWorldLoader::SpawnEntity(const TSharedPtr<FJsonObject>& EntityJson)
{
    if (!EntityJson.IsValid()) return;

    FString Name = EntityJson->GetStringField(TEXT("name"));
    const TSharedPtr<FJsonObject>* AssetUrl;
    if (EntityJson->TryGetObjectField(TEXT("assetUrl"), AssetUrl))
    {
        // TODO: resolve (*AssetUrl)->GetStringField("assetId") / "variant" to a downloaded .glb
        // (via glTFRuntime or an equivalent plugin) and spawn a real StaticMeshActor/SkeletalMesh,
        // instead of just logging — this stub intentionally does not fabricate geometry it has no
        // way to actually import in a headless code-generation context.
        UE_LOG(LogTemp, Log, TEXT("[GameWorldLoader] TODO: load asset for entity '%s'"), *Name);
    }
}
`;

export function renderUnrealHeader(vars: { worldId: string; worldName: string }): string {
  return UNREAL_HEADER_TEMPLATE.replace(/\{\{WORLD_ID\}\}/g, vars.worldId).replace(/\{\{WORLD_NAME\}\}/g, vars.worldName);
}

export function renderUnrealSource(vars: { worldId: string; worldName: string; generatedAt: string; entityCount: number }): string {
  return UNREAL_SOURCE_TEMPLATE.replace(/\{\{WORLD_ID\}\}/g, vars.worldId)
    .replace(/\{\{WORLD_NAME\}\}/g, vars.worldName)
    .replace(/\{\{GENERATED_AT\}\}/g, vars.generatedAt)
    .replace(/\{\{ENTITY_COUNT\}\}/g, String(vars.entityCount));
}
