# Secret Manager — one secret per sensitive value services/api and its workers read from the
# environment. Cloud Run services reference these directly as env vars via `secret_key_ref` in
# cloud_run.tf, so a secret rotation (new version added here) can be picked up with a redeploy
# and never needs the value to pass through a CI log or a committed file.

locals {
  secrets = {
    "jwt-secret"                    = var.jwt_secret
    "stripe-secret-key"             = var.stripe_secret_key
    "stripe-webhook-secret"         = var.stripe_webhook_secret
    "anthropic-api-key"             = var.anthropic_api_key
    "gemini-api-key"                = var.gemini_api_key
    "firebase-service-account-json" = var.firebase_service_account_json
    # Generated by this module rather than supplied — see storage.tf / database.tf / redis.tf.
    "db-user-password"    = random_password.gameworld_db_user.result
    "s3-access-key-id"    = google_storage_hmac_key.assets.access_id
    "s3-secret-access-key" = google_storage_hmac_key.assets.secret
    "redis-auth-string"   = google_redis_instance.main.auth_string
  }
}

resource "google_secret_manager_secret" "this" {
  for_each = local.secrets

  secret_id = "${var.name_prefix}-${each.key}"

  replication {
    auto {}
  }

  labels = var.labels

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "this" {
  for_each = local.secrets

  secret      = google_secret_manager_secret.this[each.key].id
  secret_data = each.value
}

# Cloud Run's runtime service account (cloud_run.tf) needs read access to each secret's latest
# version.
resource "google_secret_manager_secret_iam_member" "cloud_run_accessor" {
  for_each = local.secrets

  secret_id = google_secret_manager_secret.this[each.key].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.cloud_run.email}"
}
